# Generated by Django 4.0.3 on 2023-06-07 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0006_alter_appointment_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
    ]
