# Generated by Django 4.0.3 on 2023-06-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0007_remove_appointment_date_remove_appointment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='isVIP',
            field=models.BooleanField(default=False),
        ),
    ]
