# Generated by Django 4.0.3 on 2023-06-08 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0008_appointment_isvip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='isVIP',
        ),
    ]
