# Generated by Django 4.0.3 on 2023-06-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0009_remove_appointment_isvip'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='isVIP',
            field=models.BooleanField(default=False),
        ),
    ]
